# Generated by Django 2.1.2 on 2018-10-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20181023_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Done',
            field=models.BooleanField(default=False),
        ),
    ]
