# Generated by Django 2.1.2 on 2018-10-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='points',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
